Fix layout
beach-volley/beach-volley-app pull request #87
Opened 2021-03-14 19:33 UTC by NiklasMenard

Code refactoring, layout and CSS fixes

2021-03-14 22:00 UTC, jukkah requested changes

2021-03-14 22:00 UTC, jukkah commented on data/schema.graphql
> -
Please revert these.

2021-03-15 07:29 UTC, NiklasMenard commented on data/schema.graphql
> -
Copied schema.graphl from main

2021-03-15 15:32 UTC, jukkah approved these changes
LGTM

2021-03-19 19:01 UTC, merged